name: Configuration issue
description: Use this if you have problems installing or configuring SOLECTRUS
labels: ['help wanted']

body:
  - type: textarea
    id: description
    attributes:
      label: Description (in German or English)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: What version of SOLECTRUS are you using?
      placeholder: e.g. v0.15.0
    validations:
      required: true

  - type: input
    id: machine
    attributes:
      label: What machine are you running SOLECTRUS on?
      placeholder: e.g. Raspberry Pi 4
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Please provide logs, if applicable
      description: You can get them by running `docker compose logs`, but try to show only the relevant parts.
      render: text

  - type: textarea
    id: compose
    attributes:
      label: Please provide your `docker-compose.yml` or `compose.yml` file
      render: yaml
      placeholder: |
        e.g.:

        services:
          dashboard:
            image: ghcr.io/solectrus/solectrus:latest
        ...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Please provide your `.env` file
      description: Don't forget to anonymise all sensitive information (e.g. passwords, API keys, geo-location, etc.)
      render: text
      placeholder: |
        e.g.:

        # Domain name or IP address of your host
        APP_HOST=raspberrypi

        # Date of commissioning of your photovoltaic system
        INSTALLATION_DATE=2023-04-03
        ...
    validations:
      required: true
